---
# tasks file for cr_vm_diskfile
# create vm with diskfile in a directory

- name: create lvm
  lvol:
    vg: "{{ volumegroup }}"
    lv: "{{ hostname }}"
    size: "{{ disksize_mb }}g"

- name: create mkfs 
  command: "{{ item }}"
  with_items:
    - mkfs.ext4 /dev/{{ volumegroup }}/{{ hostname }}
  tags: lvm

- name: mount volume
  mount:
    path: "{{ basedir }}/{{ hostname }}"
    src: "/dev/mapper/{{ volumegroup }}-{{ hostname }}"
    fstype: ext4
    state: mounted
    opts: default
  tags: lvm