---
# tasks file for cr_vm_diskfile
# create vm with diskfile in a directory

- name: create lvm
  lvol:
    vg: "{{ volumegroup }}"
    lv: "{{ hostname }}"
    size: "{{ disksize_gb + overhead }}g"

- name: create fs
  filesystem:
    fstype: ext4
    dev: "/dev/mapper/{{ volumegroup }}-{{ hostname }}"
  tags: lvm

- name: mount volume
  mount:
    path: "{{ basedir }}/{{ hostname }}"
    src: "/dev/mapper/{{ volumegroup }}-{{ hostname }}"
    fstype: ext4
    state: mounted
    opts: defaults
  tags: lvm

- name: create vm
  command: >
    virt-install -n {{ hostname }} \
    --description {{ description }} \
    --os-type=Linux \
    --os-variant=centos7.0 \
    --ram={{ ramsize_mb }} \
    --vcpus={{ cpu_counts }} \
    --disk path="{{ basedir }}/{{ hostname }}/{{ hostname }}.img,bus=virtio,size={{ disksize_gb }},sparse=false,cache=none,io=native" \
    -l http://ftp.uninett.no/pub/linux/centos/7.7.1908/os/x86_64/ \
    --network bridge:br0 \
    -x "ks=http://software.ii.uib.no/kickstart/{{ hostname }}.ks ip={{ ip }} netmask=255.255.255.0 dns={{ dns }} gateway={{ gateway }}"
  tags: crvm