---
# tasks file for cr_vm_diskfile
# create vm with diskfile in a directory

- name: create lvm disk and mountpoint
  command: >
    lvcreate -L {{ disksize }}GB -n {{ hostname }} {{ volumegroup }}
    mkfs.ext4 /dev/{{ volumegroup }}/vm-{{ hostname }}